"""Generate td3port/src/symbols.h from port/symbols.csv (TDIII.EXE).

DGROUP globals          #define DS_<name>  0xXXXX            (use with DSB/DSW/DSS/DSL from mem.h)
code-segment globals    #define CS_<name>  0xXXXX            (offset in its segment, used as
                        #define CSSEG_<name> 0xSSSS            SEGB/SEGW(CSSEG_x, CS_x))
functions               #define FN_<name>  0xSSSSOOOOu        (file segment:offset, for comments/traces)
Duplicate names get an address suffix. The owner and type are kept as a comment.
"""
import csv, os, re
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
rows = list(csv.DictReader(open(os.path.join(ROOT, 'port', 'symbols.csv'), encoding='utf-8')))


def ident(name):
    name = re.sub(r'\W', '_', name)
    return ('_' + name) if name[:1].isdigit() else name


def key(r):
    a = r['address']
    if a.startswith('DS:'):
        return (0, 0, int(a[3:], 16))
    s, o = a.split(':')
    return (1, int(s, 16), int(o, 16))


def comment(r):
    typ = r['type'].replace('*/', '* /')[:48]
    return '/* %s%s */' % (r['owner'], (', ' + typ) if typ else '')


out = ['/* Generated by tools/gen_symbols.py from port/symbols.csv. Do not edit. */', '#pragma once', '']
ds = sorted((r for r in rows if r['kind'] == 'global' and r['address'].startswith('DS:')), key=key)
cs = sorted((r for r in rows if r['kind'] == 'global' and not r['address'].startswith('DS:')), key=key)
fn = sorted((r for r in rows if r['kind'] == 'func'), key=key)

for title, sel, prefix in (('DGROUP globals (offsets for DSB/DSW/DSS/DSL)', ds, 'DS_'),
                           ('Code-segment globals (CS_x offset, CSSEG_x file segment)', cs, 'CS_'),
                           ('Original functions (file segment << 16 | offset)', fn, 'FN_')):
    counts = Counter(ident(r['name']) for r in sel)
    out.append('/* ---- %s */' % title)
    for r in sel:
        n = ident(r['name'])
        k = key(r)
        if counts[n] > 1:
            n = '%s_%04X' % (n, k[2]) if k[0] == 0 else '%s_%04X_%04X' % (n, k[1], k[2])
        if prefix == 'DS_':
            out.append('#define %-44s 0x%04X  %s' % ('DS_' + n, k[2], comment(r)))
        elif prefix == 'CS_':
            out.append('#define %-44s 0x%04X  %s' % ('CS_' + n, k[2], comment(r)))
            out.append('#define %-44s 0x%04X' % ('CSSEG_' + n, k[1]))
        else:
            out.append('#define %-44s 0x%04X%04Xu  %s' % ('FN_' + n, k[1], k[2], comment(r)))
    out.append('')

dst = os.path.join(ROOT, 'td3port', 'src', 'symbols.h')
open(dst, 'w', encoding='utf-8').write('\n'.join(out))
print('wrote %s: %d DGROUP globals, %d code-segment globals, %d functions' % (dst, len(ds), len(cs), len(fn)))
